name: streaming_shared_preferences
description: A reactive key-value store for Flutter projects, built on top of shared_preferences.
version: 1.0.0-dev-5
author: Iiro Krankka <iiro.krankka@gmail.com>
homepage: https://github.com/roughike/streaming_shared_preferences

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.0
  meta: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.0.0
  mockito: ^4.0.0